server:
  port: 80
  servlet:
    context-path: /aaa

spring:
    application:
        name: now
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/qgpt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        platform: mysql
        druid:
          initial-size: 3
          max-active: 20 
              
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: classpath:com.reward.now.bean
    
    
logging:
  file: /log/now.log
  level: 
    com.reward.now.dao: DEBUG
    com.reward.now.controller: DEBUG
    org.springframework.web: DEBUG
 
    
 